// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: employee.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmployeeClient is the client API for Employee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeClient interface {
	// 一元消息
	GetByNo(ctx context.Context, in *GetByNoRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	// server stream
	// 获取所有员工
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (Employee_GetAllClient, error)
	// client stream
	// 上传头像信息
	AllPhoto(ctx context.Context, opts ...grpc.CallOption) (Employee_AllPhotoClient, error)
	// 双向stream
	// 上传employee信息
	Save(ctx context.Context, in *SaveEmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	SaveAll(ctx context.Context, opts ...grpc.CallOption) (Employee_SaveAllClient, error)
}

type employeeClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeClient(cc grpc.ClientConnInterface) EmployeeClient {
	return &employeeClient{cc}
}

func (c *employeeClient) GetByNo(ctx context.Context, in *GetByNoRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/Employee/GetByNo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (Employee_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &Employee_ServiceDesc.Streams[0], "/Employee/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Employee_GetAllClient interface {
	Recv() (*EmployeeResponse, error)
	grpc.ClientStream
}

type employeeGetAllClient struct {
	grpc.ClientStream
}

func (x *employeeGetAllClient) Recv() (*EmployeeResponse, error) {
	m := new(EmployeeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *employeeClient) AllPhoto(ctx context.Context, opts ...grpc.CallOption) (Employee_AllPhotoClient, error) {
	stream, err := c.cc.NewStream(ctx, &Employee_ServiceDesc.Streams[1], "/Employee/AllPhoto", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeAllPhotoClient{stream}
	return x, nil
}

type Employee_AllPhotoClient interface {
	Send(*AddPhotoRequest) error
	CloseAndRecv() (*AddPhotoResponse, error)
	grpc.ClientStream
}

type employeeAllPhotoClient struct {
	grpc.ClientStream
}

func (x *employeeAllPhotoClient) Send(m *AddPhotoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *employeeAllPhotoClient) CloseAndRecv() (*AddPhotoResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddPhotoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *employeeClient) Save(ctx context.Context, in *SaveEmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/Employee/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) SaveAll(ctx context.Context, opts ...grpc.CallOption) (Employee_SaveAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &Employee_ServiceDesc.Streams[2], "/Employee/SaveAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeSaveAllClient{stream}
	return x, nil
}

type Employee_SaveAllClient interface {
	Send(*SaveEmployeeRequest) error
	Recv() (*EmployeeResponse, error)
	grpc.ClientStream
}

type employeeSaveAllClient struct {
	grpc.ClientStream
}

func (x *employeeSaveAllClient) Send(m *SaveEmployeeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *employeeSaveAllClient) Recv() (*EmployeeResponse, error) {
	m := new(EmployeeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmployeeServer is the server API for Employee service.
// All implementations must embed UnimplementedEmployeeServer
// for forward compatibility
type EmployeeServer interface {
	// 一元消息
	GetByNo(context.Context, *GetByNoRequest) (*EmployeeResponse, error)
	// server stream
	// 获取所有员工
	GetAll(*GetAllRequest, Employee_GetAllServer) error
	// client stream
	// 上传头像信息
	AllPhoto(Employee_AllPhotoServer) error
	// 双向stream
	// 上传employee信息
	Save(context.Context, *SaveEmployeeRequest) (*EmployeeResponse, error)
	SaveAll(Employee_SaveAllServer) error
	mustEmbedUnimplementedEmployeeServer()
}

// UnimplementedEmployeeServer must be embedded to have forward compatible implementations.
type UnimplementedEmployeeServer struct {
}

func (UnimplementedEmployeeServer) GetByNo(context.Context, *GetByNoRequest) (*EmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByNo not implemented")
}
func (UnimplementedEmployeeServer) GetAll(*GetAllRequest, Employee_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedEmployeeServer) AllPhoto(Employee_AllPhotoServer) error {
	return status.Errorf(codes.Unimplemented, "method AllPhoto not implemented")
}
func (UnimplementedEmployeeServer) Save(context.Context, *SaveEmployeeRequest) (*EmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedEmployeeServer) SaveAll(Employee_SaveAllServer) error {
	return status.Errorf(codes.Unimplemented, "method SaveAll not implemented")
}
func (UnimplementedEmployeeServer) mustEmbedUnimplementedEmployeeServer() {}

// UnsafeEmployeeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeServer will
// result in compilation errors.
type UnsafeEmployeeServer interface {
	mustEmbedUnimplementedEmployeeServer()
}

func RegisterEmployeeServer(s grpc.ServiceRegistrar, srv EmployeeServer) {
	s.RegisterService(&Employee_ServiceDesc, srv)
}

func _Employee_GetByNo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).GetByNo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Employee/GetByNo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).GetByNo(ctx, req.(*GetByNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmployeeServer).GetAll(m, &employeeGetAllServer{stream})
}

type Employee_GetAllServer interface {
	Send(*EmployeeResponse) error
	grpc.ServerStream
}

type employeeGetAllServer struct {
	grpc.ServerStream
}

func (x *employeeGetAllServer) Send(m *EmployeeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Employee_AllPhoto_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServer).AllPhoto(&employeeAllPhotoServer{stream})
}

type Employee_AllPhotoServer interface {
	SendAndClose(*AddPhotoResponse) error
	Recv() (*AddPhotoRequest, error)
	grpc.ServerStream
}

type employeeAllPhotoServer struct {
	grpc.ServerStream
}

func (x *employeeAllPhotoServer) SendAndClose(m *AddPhotoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *employeeAllPhotoServer) Recv() (*AddPhotoRequest, error) {
	m := new(AddPhotoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Employee_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Employee/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).Save(ctx, req.(*SaveEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_SaveAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServer).SaveAll(&employeeSaveAllServer{stream})
}

type Employee_SaveAllServer interface {
	Send(*EmployeeResponse) error
	Recv() (*SaveEmployeeRequest, error)
	grpc.ServerStream
}

type employeeSaveAllServer struct {
	grpc.ServerStream
}

func (x *employeeSaveAllServer) Send(m *EmployeeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *employeeSaveAllServer) Recv() (*SaveEmployeeRequest, error) {
	m := new(SaveEmployeeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Employee_ServiceDesc is the grpc.ServiceDesc for Employee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Employee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Employee",
	HandlerType: (*EmployeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByNo",
			Handler:    _Employee_GetByNo_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _Employee_Save_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _Employee_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AllPhoto",
			Handler:       _Employee_AllPhoto_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SaveAll",
			Handler:       _Employee_SaveAll_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "employee.proto",
}
